text_labeller/create_projects/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms.validators import DataRequired


class PrepareDataForm(FlaskForm):
    title = StringField('Project Title', validators=[DataRequired()])
    content = FileField('Upload Data', validators=[FileAllowed(['csv']), FileRequired()])
    class_labels = StringField('Class Labels (separate with comma e.g. negative, positive, neutral)', validators=[DataRequired()])
    submit = SubmitField('Submit')

text_labeller/label_data/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, RadioField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms.validators import DataRequired, InputRequired


class SelectProjectForm(FlaskForm):
    project = SelectField('Select Project to Label', coerce=int, validators=[InputRequired()])
    submit = SubmitField('Submit')


class LabelDataForm(FlaskForm):
    class_label= RadioField('Select Label', coerce=int, validators=[InputRequired()])
    submit = SubmitField('Submit')

text_labeller/view_data/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, SelectField, RadioField
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms.validators import DataRequired, InputRequired


class SelectProjectForm(FlaskForm):
    project = SelectField('Select Project to View', coerce=int, validators=[InputRequired()])
    submit = SubmitField('Submit')

text_labeller/create_projects/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint)
from flask_login import current_user, login_required
from text_labeller import db
from text_labeller.create_projects.forms import PrepareDataForm
from io import TextIOWrapper
import csv
from text_labeller.models import Project, Text, Class_Labels
from werkzeug.utils import secure_filename
import os
import pandas as pd

create_projects = Blueprint('create_projects', __name__)


@create_projects.route("/prepare_data", methods=['GET', 'POST'])
@login_required
def create_project():
    form = PrepareDataForm()
    if form.validate_on_submit():
        if request.method == 'POST':
            project = Project(title=form.title.data, user_id=current_user.user_id)
            db.session.add(project)
            db.session.commit()
    
            form_text_data = form.content.data
            uploaded_filename= secure_filename(form_text_data.filename)
            form_text_data.save(uploaded_filename)
            df = pd.read_csv(uploaded_filename)

            for index, row in df.iterrows():
                text = Text(text = row[0], project_id = project.project_id)
                db.session.add(text)
                db.session.commit()

            class_labels = form.class_labels.data.split(',')
            for label in class_labels:
                label = label.strip()
                class_label = Class_Labels(class_label = label, project_id = project.project_id)
                db.session.add(class_label)
                db.session.commit()

            flash('Your project has been created, you can now start labelling!', 'success')
            return redirect(url_for('label_data.select_project'))
            
    return render_template('create_project.html', title='Create Project', form=form)

text_labeller/label_data/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, session)
from flask_login import current_user, login_required
from text_labeller import db
from text_labeller.label_data.forms import SelectProjectForm, LabelDataForm
from text_labeller.models import Project, Text, Class_Labels, User

label_data = Blueprint('label_data', __name__)


@label_data.route('/select_project', methods=['GET', 'POST'])
@login_required
def select_project():
    available_projects=db.session.query(Project).filter(Project.user_id == current_user.user_id).all()
    #get the list of tuples for SelectField
    projects_list=[(i.project_id, i.title) for i in available_projects]
    select_form=SelectProjectForm()
    #passing projects_list to the form
    select_form.project.choices = projects_list

    if select_form.validate_on_submit():
        if request.method == 'POST':
            # not working showing an id
            selected_project_name = dict(select_form.project.choices).get(select_form.project.data)
            selected_project_id =  select_form.project.data
            session['selected_project_id'] = selected_project_id

            flash('Project Selected', 'success')
            return redirect(url_for('label_data.label_data_class'))

    return render_template('select_project.html', title='Select Project', form=select_form)


@label_data.route('/label_data', methods=['GET', 'POST'])
@login_required
def label_data_class():
    # we need to get the project id the user selected that they want to label so we cant filter to that data
    # we will use a session to do this
    selected_id_by_user = session['selected_project_id']
    available_labels=db.session.query(Class_Labels).filter(Class_Labels.project_id == selected_id_by_user).all()
    text_to_label_query=db.session.query(Text).filter(Text.class_label_id == None, Text.project_id == selected_id_by_user).first()


    if text_to_label_query != None:
        text_to_label=text_to_label_query.text
        id_of_text=db.session.query(Text).filter(Text.class_label_id == None, Text.project_id == selected_id_by_user).first().text_id

        labels_list=[(i.class_label_id, i.class_label) for i in available_labels] 
        label_data_form=LabelDataForm()
        #passing projects_list to the form
        label_data_form.class_label.choices = labels_list
        text_row = Text.query.get(id_of_text)

        if label_data_form.validate_on_submit():
            if request.method == 'POST':

                text_row.class_label_id = label_data_form.class_label.data
                db.session.commit()

                flash('Data Labelled', 'success')
                return redirect(url_for('label_data.label_data_class'))

    else:
        return render_template('no_data.html')

    return render_template('label_data.html', title='Label Data', form=label_data_form, text_to_label=text_to_label)

text_labeller/main/routes.py
from flask import render_template, request, Blueprint

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    return render_template('home.html')

text_labeller/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from text_labeller import db, bcrypt
from text_labeller.models import User
from text_labeller.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from text_labeller.users.utils import send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        # user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        user = User(email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

text_labeller/view_data/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, session, send_file, make_response)
from flask_login import current_user, login_required
from text_labeller import db
from text_labeller.view_data.forms import SelectProjectForm
from text_labeller.models import Project, Text, Class_Labels, User
import pandas as pd

view_data_blueprint = Blueprint('view_data', __name__)


@view_data_blueprint.route('/select_project_to_view', methods=['GET', 'POST'])
@login_required
def select_project_to_view():
    available_projects=db.session.query(Project).filter(Project.user_id == current_user.user_id).all()
    #get the list of tuples for SelectField
    projects_list=[(i.project_id, i.title) for i in available_projects]
    select_form=SelectProjectForm()
    #passing projects_list to the form
    select_form.project.choices = projects_list

    if select_form.validate_on_submit():
        if request.method == 'POST':
            # not working showing an id
            selected_project_name = dict(select_form.project.choices).get(select_form.project.data)
            selected_project_id =  select_form.project.data
            session['selected_project_name'] = selected_project_name
            session['selected_project_id'] = selected_project_id

            flash(f'Project Selected', 'success')
            return redirect(url_for('view_data.view_data'))

    return render_template('select_project_to_show.html', title='Select Project', form=select_form)


@view_data_blueprint.route('/view_data', methods=['GET'])
@login_required
def view_data():
    # we need to get the project id the user selected that they want to label so we cant filter to that data
    # we will use a session to do this
    selected_id_by_user = session['selected_project_id']
    selected_project_name_by_user = session['selected_project_name']
    text_to_show_query=db.session.query(Text, Class_Labels).join(Class_Labels, Text.class_label_id == Class_Labels.class_label_id).filter(Class_Labels.project_id == selected_id_by_user).statement
    text_to_show=pd.read_sql(text_to_show_query, db.session.bind)
    text_to_show = text_to_show[['text', 'class_label']]
    text_to_show.columns = ['Text', 'Label']

    return render_template('view_data.html',  tables=[text_to_show.to_html()], titles=text_to_show.columns.values, project_name=selected_project_name_by_user)

@view_data_blueprint.route('/download_data', methods=['GET'])
@login_required
def download_data():
    # we need to get the project id the user selected that they want to label so we cant filter to that data
    # we will use a session to do this
    selected_id_by_user = session['selected_project_id']
    selected_project_name_by_user = session['selected_project_name']
    text_to_show_query=db.session.query(Text, Class_Labels).join(Class_Labels, Text.class_label_id == Class_Labels.class_label_id).filter(Class_Labels.project_id == selected_id_by_user).statement
    text_to_show=pd.read_sql(text_to_show_query, db.session.bind)
    text_to_show = text_to_show[['text', 'class_label']]
    text_to_show.columns = ['Text', 'Label']

    response = make_response(text_to_show.to_csv())
    response.headers["Content-Disposition"] = "attachment; filename=data.csv"
    response.headers["Content-Type"] = "text/csv"
    return response

text_labeller/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

text_labeller/templates/create_project.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="", enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.class_labels.label(class="form-control-label") }}
                {% if form.class_labels.errors %}
                    {{ form.class_labels(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.class_labels.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.class_labels(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

text_labeller/templates/home.html
{% extends "layout.html" %}
{% block content %}
<h3>TextLabeller is a free platform for labelling data for text classification tasks. Follow the steps below to start labelling &#x1F60A; </h3>
<!-- <h5>Steps to label text data: </h5>-->
<hr></hr> 
<p1>1. Register as a user or login</p1>
<br></br>
<p1>2. Create a project which includes uploading a CSV file containing one column of text data and providing the classes you want to label your data into </p1>
<br></br>
<p1>3. Go to the label data tab and select your project </p1>
<br></br>
<p1>4. Start labelling! </p1>
<br></br>
<p1>5. View and download your labelled data &nbsp; &#127881; &#127881; </p1>
<style>
    h3{ 
    	text-align: center;
    }
</style>

{% endblock content %}

text_labeller/templates/label_data.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="", enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <br></br>
            <h4>{{text_to_label}}</h4>
            <br></br>
            <div class="form-group">
                {{ form.class_label.label(class="form-control-label") }}
                {% if form.class_label.errors %}
                    {{ form.class_label(class="form-control form-control-lg is-invalid", style="list-style:none") }}
                    <div class="invalid-feedback">
                        {% for error in form.class_label.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.class_label(style="list-style:none") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

text_labeller/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>TextLabeller - {{ title }}</title>
    {% else %}
        <title>TextLabeller</title>
    {% endif %}
</head>
<body>
    <header class="site-header">
      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
        <div class="container">
          <a class="navbar-brand mr-4" href="/">TextLabeller</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarToggle">
            <div class="navbar-nav mr-auto">
              <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>
            </div>
            <!-- Navbar Right Side -->
            <div class="navbar-nav">
              {% if current_user.is_authenticated %}
                <a class="nav-item nav-link" href="{{ url_for('create_projects.create_project') }}">Create Project</a>
                <a class="nav-item nav-link" href="{{ url_for('label_data.select_project') }}">Label Data</a>
                <a class="nav-item nav-link" href="{{ url_for('view_data.select_project_to_view') }}">View / Download Data</a>
                <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
              {% else %}
                <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
              {% endif %}
            </div>
          </div>
        </div>
      </nav>
    </header>
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
          {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
                <div class="alert alert-{{ category }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
          {% endwith %}
          {% block content %}{% endblock %}
        </div>
      </div>
    </main>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

text_labeller/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

text_labeller/templates/no_data.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
   <p1>There is no more data to label</p1>
</div>
{% endblock content %}

text_labeller/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Join Today</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already Have An Account? <a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
        </small>
    </div>
{% endblock content %}

text_labeller/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

text_labeller/templates/select_project.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="", enctype="multipart/form-data">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <div class="form-group">
                {{ form.project.label(class="form-control-label") }}
                {% if form.project.errors %}
                    {{ form.project(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.project.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.project(class="form-control form-control-lg") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock content %}

text_labeller/templates/view_data.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
	<H4>{{project_name}} - Data</H4>
	    <div class="row">
        <div class="col-md-4">
        </div>
      <div class="col">
        {{download_csv | safe}}
      </br></br>
        <a class="btn btn-primary" href="{{ url_for('view_data.download_data') }}" role="button">Download Data as CSV</a>
    </div>
    </div>
    </br></br>

	{% for table in tables %}
            {{ table|safe }}   
	{% endfor %}
</div>
<style>

    .btn-primary{ 
        margin-left: auto;
        margin-right: auto;
        border: 1px solid black;
        width: 50%;
        text-align: center;
    }

    table { 
        margin-left: auto;
        margin-right: auto;
        border: 1px solid black;
        width: 80%;
    }
    table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
    }
    th, td {
        padding: 20px;
        text-align: center;
        font-family: Helvetica, Arial, sans-serif;
        font-size: 90%;
        border: 1px solid black;
    }
    table tbody tr:hover {
        background-color: #dddddd;
    }
    h4{
    	text-align: center;
    }

</style>
{% endblock content %}